# Generated by Django 2.2.5 on 2019-12-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
